const USER_ACTION = {
    ADD: "ADD_IN_CART",
    ADD_ALL: "ADD_ALL_IN_CART",
    ADD_TO_WISH: "ADD_TO_WISH",
    REMOVE_FROM_WISH: "REMOVE_FROM_WISH",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    REMOVE_ALL_FROM_CART: "REMOVE_ALL_FROM_CART",
}

export { USER_ACTION };